apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: efidemos/${{values.component_id }}
    sonarqube.org/project-key: efidemos/${{values.component_id }}
spec:
  type: repository
  lifecycle: experimental
  owner: ${{values.owner | dump}}
